application: dirksen-library
version: 1
runtime: go
api_version: go1

handlers:
# re-direct to index.html if no path is give
- url: /
  static_files: index.html
  upload: index.html
- url: /index.html
  static_files: index.html
  upload: index.html
- url: /about.html
  static_files: about.html
  upload: about.html
- url: /helpful.html
  static_files: helpful.html
  upload: helpful.html

# access the static resources in the root director
- url: /css/(.*)
  static_files: css/\1
  upload: css/(.*)
# access the static resources in the root director
- url: /img/(.*)
  static_files: img/\1
  upload: img/(.*)
# access the static resources in the root director
- url: /img/svg/(.*)
  static_files: img/svg/\1
  upload: img/svg/(.*)