application: dirksen-library
version: 1
runtime: go
api_version: go1

handlers:
# re-direct to index.html if no path is give
- url: /
  static_files: index.html
  upload: index.html
- url: /index.html
  static_files: index.html
  upload: index.html
- url: /about.html
  static_files: about.html
  upload: about.html
- url: /helpful.html
  static_files: helpful.html
  upload: helpful.html
- url: /custom/justified-nav.css
  static_files: custom/justified-nav.css
  upload: custom/justified-nav.css
- url: /custom/library.css
  static_files: custom/library.css
  upload: custom/library.css

# access the static resources in the root director
- url: /img/(.*)
  static_files: img/\1
  upload: img/(.*)